apiVersion: stable.helm.operator.io/v1
kind: Chart
metadata:
  name: nginx
  namespace: test
spec:
  chart: nginx-ingress
  repo: stable
  version: 1.5.0
  nameSpaceSelector: "default"
  values:
  - name: controller.name
    value: foo
  - name: controller.autoscaling.enabled
    value: "true"
